# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
     - task: CmdLine@2
       displayName: Install Checkov for IaC Scan
       inputs:
          script: |
            python -m pip install --upgrade pip
            pip install checkov
      
     - task: CmdLine@2
       displayName: Checkov IaC Scan
       inputs:
        script: | 
          checkov -d . --output junitxml --output-file-path checkov-junit-report.xml

     - task: PublishTestResults@2
       displayName: 'Publish Checkov Test Results'
       inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/checkov-junit-report.xml'
        failTaskOnFailedTests: true
        testRunTitle: 'Checkov IaC Security Scan'
        
          
     - task: Docker@2
       displayName: Build an image
       inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)